# memory_folder: ./src/database/memory
# conversation: ./src/database/conversation/conversation.pkl


redis:
  auth: OLredis~2023
  ip: localhost
  port: 8379
  db: 1

mongo:
  ip: localhost
  port: 27017
  db: ai_memory
  user: mongoadmin
  passwd: OLmongo2024

redis:
  ip: localhost
  port: 27017
  db: ai_memory
  user: mongoadmin
  passwd: OLmongo2024